### ISSUE TITLE
iOS build broken: ambiguous greatestFiniteMagnitude in SigxRichTextUI.swift (Xcode 26)

### ISSUE THREAD

**Issue by andtii** [signalxjs/lynx#204]
## Problem

`sigx run:ios` fails for any app using `@sigx/lynx-richtext` since #200:

```
SigxRichTextUI.swift:59:73: error: ambiguous use of 'greatestFiniteMagnitude'
SigxRichTextUI.swift:69:33: error: cannot infer contextual base in reference to member 'clear'
** BUILD FAILED **
```

`CGSize(width: 0, height: .greatestFiniteMagnitude)` — with the integer literal `0`, Swift can't settle on Double/CGFloat for the member lookup, so the init is ambiguous (line 69 is a cascade: the failed `container` breaks `view`'s type inference). Reproduced with Xcode 26.0.1 building `examples/showcase`. CI doesn't compile the example's native project, which is why it landed green.

## Fix

Qualify the type: `CGSize(width: 0, height: CGFloat.greatestFiniteMagnitude)` in `packages/lynx-richtext/ios/SigxRichTextUI.swift`. One line.
